
interface ProfileImage {
    public_id: string;
    url: string;
  }
  
  interface Member {
    profile_image: ProfileImage;
    _id: string;
    name: string;
    department: string;
    designation: string;
    email_id: string;
    batch: string;
    bio: string;
    github_url: string;
    linkedin_url: string;
    leader: boolean;
    createdAt: string;
    updatedAt: string;
    __v: number;
  }
  
  interface Data {
    success: boolean;
    members: Member[];
  }
  
const data: Data = {
    success: true,
    members: [
      {
        profile_image: {
          public_id: "avatars/wldgrsvnmuxffglxzdu8",
          url: "https://res.cloudinary.com/dd1rpkqom/image/upload/v1726147439/avatars/wldgrsvnmuxffglxzdu8.jpg",
        },
        _id: "66e2eb6c7f335bb5a49eedf5",
        name: "Khushi Bohra",
        department: "CSE-DS",
        designation: "President",
        email_id: "khushibohra0@gmail.com",
        batch: "2021-25",
        bio: "Front end developer || Data Analyst",
        github_url: "https://github.com/khushibohra1402",
        linkedin_url: "https://www.linkedin.com/in/khushi-bohra-241701239/",
        leader: true,
        createdAt: "2024-09-12T13:23:56.331Z",
        updatedAt: "2024-09-12T13:23:56.331Z",
        __v: 0,
      },
      {
        profile_image: {
          public_id: "avatars/bwcarsd7kset9fuqr1c8",
          url: "https://res.cloudinary.com/dd1rpkqom/image/upload/v1726148443/avatars/bwcarsd7kset9fuqr1c8.jpg",
        },
        _id: "66e2ef577f335bb5a49eee03",
        name: "Harsh Shankar Prasad",
        department: "CSE-DS",
        designation: "Vice-President",
        email_id: "harshshankar674@gmail.com",
        batch: "2021-25",
        bio: "I’m a Computer Science and Engineering student specializing in Data Science. As the Vice-President of our tech society, I leverage my leadership skills and logical decision-making to drive growth and innovation within the society.",
        github_url: "https://github.com/harshshankarpd",
        linkedin_url: "https://www.linkedin.com/in/harshshankarpd",
        leader: true,
        createdAt: "2024-09-12T13:40:39.869Z",
        updatedAt: "2024-09-12T13:40:39.869Z",
        __v: 0,
      },
      {
        profile_image: {
          public_id: "avatars/jasqeshashx8ag8osif2",
          url: "https://res.cloudinary.com/dd1rpkqom/image/upload/v1726155263/avatars/jasqeshashx8ag8osif2.jpg",
        },
        _id: "66e309fc7f335bb5a49eee0c",
        name: "Ashish Kishu ",
        department: "CSE-DS",
        designation: "Secretary",
        email_id: "ashishkishu0210@gmail.com",
        batch: "2021-25",
        bio: "A self motivated , responsible and an enthusiastic person, with a creative mind and strong work ethic.I find myself dedicated and passionate towards work and always trying to excel with skillset aligned to my interests. I'm passionate about contributing positively to my community and I am always eager to take on new challenges.",
        github_url: "https://github.com/ashishkishusrepo",
        linkedin_url: "https://www.linkedin.com/in/ashish-kishu-2611b721b/",
        leader: true,
        createdAt: "2024-09-12T15:34:20.008Z",
        updatedAt: "2024-09-12T15:34:20.008Z",
        __v: 0,
      },
      {
        profile_image: {
          public_id: "avatars/wrhks112zlcql517pq2d",
          url: "https://res.cloudinary.com/dd1rpkqom/image/upload/v1726155607/avatars/wrhks112zlcql517pq2d.jpg",
        },
        _id: "66e30b547f335bb5a49eee12",
        name: "Srishti Srivastava",
        department: "CSE-DS",
        designation: "Treasurer",
        email_id: "srivastavasrishti073@gmail.com",
        batch: "2021-25",
        bio: "A highly motivated technology professional with a strong passion for Data science. Dedicated to achieving excellence through continuous learning and innovation.",
        github_url: "https://github.com/Srishtisri22",
        linkedin_url: "www.linkedin.com/in/srishti-srivastava-a0b8a623a",
        leader: true,
        createdAt: "2024-09-12T15:40:04.364Z",
        updatedAt: "2024-09-12T15:40:04.364Z",
        __v: 0,
      },
      {
        profile_image: {
          public_id: "avatars/tbppqy0redllfpvqbvws",
          url: "https://res.cloudinary.com/dxmvkaoql/image/upload/v1726650929/avatars/tbppqy0redllfpvqbvws.jpg",
        },
        _id: "66ea9a32e6f247cbfce657cd",
        name: "Ankit Raj",
        department: "CSE-DS",
        designation: "Technical Head",
        email_id: "na@gmail.com",
        batch: "2021-25",
        bio: " ",
        github_url: "NA",
        linkedin_url: "NA",
        leader: true,
        createdAt: "2024-09-18T09:15:30.279Z",
        updatedAt: "2024-09-18T09:15:30.279Z",
        __v: 0,
      },
      {
        profile_image: {
          public_id: "avatars/zscaoi0137huuawb55kr",
          url: "https://res.cloudinary.com/dxmvkaoql/image/upload/v1726650985/avatars/zscaoi0137huuawb55kr.jpg",
        },
        _id: "66ea9a69e6f247cbfce657d2",
        name: "Shubham Kumar",
        department: "CSE-DS",
        designation: "Event Head",
        email_id: "na@gmail.com",
        batch: "2021-25",
        bio: " ",
        github_url: "NA",
        linkedin_url: "NA",
        leader: true,
        createdAt: "2024-09-18T09:16:25.466Z",
        updatedAt: "2024-09-18T09:16:25.466Z",
        __v: 0,
      },
      {
        profile_image: {
          public_id: "avatars/jwffwcqredoce8v1pgap",
          url: "https://res.cloudinary.com/dxmvkaoql/image/upload/v1726651144/avatars/jwffwcqredoce8v1pgap.jpg",
        },
        _id: "66ea9b08e6f247cbfce657d9",
        name: "Utsav Raj",
        department: "CSE-DS",
        designation: "Media Head",
        email_id: "utsavraj2892@gmail.com",
        batch: "2021-25",
        bio: "freelance data engineer with expertise in handling data-related projects",
        github_url: "https://github.com/UTSAVRAJ28",
        linkedin_url: "https://www.linkedin.com/in/utsav-raj-676a9b1aa",
        leader: true,
        createdAt: "2024-09-18T09:19:04.683Z",
        updatedAt: "2024-09-18T09:19:04.683Z",
        __v: 0,
      },
      {
        profile_image: {
          public_id: "avatars/o2izwrgnfnt5qc4jv8sv",
          url: "https://res.cloudinary.com/dxmvkaoql/image/upload/v1726651386/avatars/o2izwrgnfnt5qc4jv8sv.png",
        },
        _id: "66ea9bfbe6f247cbfce657df",
        name: "MD Saquib",
        department: "CSE-DS",
        designation: "PR Head",
        email_id: "saquibansari17958@gmail.com",
        batch: "2021-25",
        bio: "The more you think about how little you understand, the more you realize how much there is to learn.\nI’m just an engineer trying to live my life.\nEngineering is all about designing creative solutions to real-world problems.\nEngineering is the art of doing that which isn’t necessary in order to achieve that which is possible.\nAs engineer I also love problems, and if there are not any, they will create my own.",
        github_url: "https://github.com/MdSaquib123",
        linkedin_url: "https://www.linkedin.com/in/md-saquib-4b975523b",
        leader: true,
        createdAt: "2024-09-18T09:23:07.036Z",
        updatedAt: "2024-09-18T09:23:07.036Z",
        __v: 0,
      },
      {
        profile_image: {
          public_id: "avatars/gw53e0u74svwbjgelezi",
          url: "https://res.cloudinary.com/dxmvkaoql/image/upload/v1726651519/avatars/gw53e0u74svwbjgelezi.png",
        },
        _id: "66ea9c7fe6f247cbfce657e4",
        name: "Shruti Suman",
        department: "CSE-DS",
        designation: "PR Head",
        email_id: "shrutisuman0651@gmail.com",
        batch: "2021-25",
        bio: "As an enthusiastic CSE-DS student, I have a strong foundation in data structures and algorithms and have experience in development and design. I am known for my \nexcellent problem-solving skills and have a proficiency in C, C++, Java, and Web development. I am also actively learning about data science and machine \nlearning. In addition, I have the ability to quickly learn new software, tools, and technologies, making me a valuable asset to any team.",
        github_url: "https://github.com/shrutiisuman",
        linkedin_url: "https://www.linkedin.com/in/shruti-suman-116b88230/",
        leader: true,
        createdAt: "2024-09-18T09:25:19.628Z",
        updatedAt: "2024-09-18T09:25:19.628Z",
        __v: 0,
      },
      {
        profile_image: {
          public_id: "avatars/pavkvxxgj24mnxn6zzex",
          url: "https://res.cloudinary.com/dd1rpkqom/image/upload/v1730797904/avatars/pavkvxxgj24mnxn6zzex.jpg",
        },
        _id: "6729d87685836f387a683cde",
        name: "Ayush Kumar",
        department: "CSE-DS",
        designation: "Technical Member",
        email_id: "ayushjha4wd@gmail.com",
        batch: "2022-26",
        bio: "I am eager to contribute to the fields of technology and research, particularly in Artificial Intelligence and Data Science.",
        github_url: "https://github.com/ayushjha4wd",
        linkedin_url: "https://www.linkedin.com/in/ayush-kumar-9b48ba24b/",
        leader: false,
        createdAt: "2024-11-05T08:33:58.360Z",
        updatedAt: "2024-11-05T09:11:44.558Z",
        __v: 0,
      },
      {
        profile_image: {
          public_id: "avatars/pybefhpfneuciavfzjp2",
          url: "https://res.cloudinary.com/dd1rpkqom/image/upload/v1730796026/avatars/pybefhpfneuciavfzjp2.jpg",
        },
        _id: "6729d9fa85836f387a683d16",
        name: "Ayush Raj",
        department: "CSE-DS",
        designation: "Technical Member",
        email_id: "itisayushraj17@gmail.com",
        batch: "2022-26",
        bio: "I am enthusiast web developer and ml programmer. I  love solving real life problems. \n",
        github_url: "https://github.com/AyushABD-17",
        linkedin_url: "https://www.linkedin.com/in/ayush-raj-87b8282a3",
        leader: false,
        createdAt: "2024-11-05T08:40:26.583Z",
        updatedAt: "2024-11-05T08:40:26.583Z",
        __v: 0,
      },
      {
        profile_image: {
          public_id: "avatars/lmnevmgbbxx4hu1s54nw",
          url: "https://res.cloudinary.com/dd1rpkqom/image/upload/v1730796136/avatars/lmnevmgbbxx4hu1s54nw.png",
        },
        _id: "6729da6885836f387a683d1c",
        name: "Deepak kumar",
        department: "CSE-DS",
        designation: "Technical Member",
        email_id: "deepakjamui26@gmail.com",
        batch: "2022-26",
        bio: "Full Stack Developer and Data Science student, passionate about building impactful tech solutions.",
        github_url: "https://github.com/deepak-raaaz",
        linkedin_url: "https://www.linkedin.com/in/deepak-raaaz/",
        leader: false,
        createdAt: "2024-11-05T08:42:16.664Z",
        updatedAt: "2024-11-05T08:42:16.664Z",
        __v: 0,
      },
      {
        profile_image: {
          public_id: "avatars/ehro2xkmcd1smwod0hwm",
          url: "https://res.cloudinary.com/dd1rpkqom/image/upload/v1730796571/avatars/ehro2xkmcd1smwod0hwm.png",
        },
        _id: "6729dc1b85836f387a683d22",
        name: "Prasun Maity ",
        department: "CSE-DS",
        designation: "Technical Member",
        email_id: "maitypro402@gmail.com",
        batch: "2022-26",
        bio: "An enthusiastic tech geek passionate about Data Analytics and Data Science, adept at transforming data into actionable insights through innovative solutions and advanced technologies. Known for solving complex problems and optimizing model performance, committed to harnessing data's power for impactful decisions.",
        github_url: "https://github.com/pro402",
        linkedin_url: "www.linkedin.com/in/pro402",
        leader: false,
        createdAt: "2024-11-05T08:49:31.949Z",
        updatedAt: "2024-11-05T08:49:31.949Z",
        __v: 0,
      },
      {
        profile_image: {
          public_id: "avatars/qc2jv11y6rbazsj7bbr4",
          url: "https://res.cloudinary.com/dd1rpkqom/image/upload/v1731343836/avatars/qc2jv11y6rbazsj7bbr4.jpg",
        },
        _id: "673235dd13d01b8bc184a97b",
        name: "Abhishek Singh",
        department: "CSE",
        designation: "PR",
        email_id: "abhisingh4740@gmail.com",
        batch: "2022-26",
        bio: "I chose this for my speaking and problem solving skills in a group of people.",
        github_url: "https://github.com/Abhisinghhhh",
        linkedin_url:
          "https://www.linkedin.com/in/abhishek-singh-4ba9b3277?utm_source=share&utm_campaign=share_via&utm_content=profile&utm_medium=android_app",
        leader: false,
        createdAt: "2024-11-11T16:50:37.194Z",
        updatedAt: "2024-11-11T16:50:37.194Z",
        __v: 0,
      },
      {
        profile_image: {
          public_id: "avatars/c8jpkexkd4igpbb7qn0e",
          url: "https://res.cloudinary.com/dd1rpkqom/image/upload/v1731384820/avatars/c8jpkexkd4igpbb7qn0e.jpg",
        },
        _id: "6732d5f513d01b8bc184b13c",
        name: "Artisha Banerjee",
        department: "CSE-DS",
        designation: "PR",
        email_id: "artishabanerjee0@gmail.com",
        batch: "2022-26",
        bio: "Data is the blood of our body called the IT industry.\n",
        github_url: "https://github.com/Artishabanerjee",
        linkedin_url:
          "https://www.linkedin.com/in/artisha-banerjee-4246a0289?utm_source=share&utm_campaign=share_via&utm_content=profile&utm_medium=android_app",
        leader: false,
        createdAt: "2024-11-12T04:13:41.345Z",
        updatedAt: "2024-11-12T04:13:41.345Z",
        __v: 0,
      },
      {
        profile_image: {
          public_id: "avatars/qbkvy3cnmywym6vkwewb",
          url: "https://res.cloudinary.com/dd1rpkqom/image/upload/v1731385021/avatars/qbkvy3cnmywym6vkwewb.jpg",
        },
        _id: "6732d6bd13d01b8bc184b141",
        name: "Anshika Kumari",
        department: "CSE-DS",
        designation: "PR",
        email_id: "kumarianshika2910@gmail.com",
        batch: "2022-26",
        bio: "I am a dedicated PR specialist with a strong background in effective communication and strategic engagement. Leveraging my expertise in crafting impactful messages and building relationships, I excel at influencing public perception and fostering meaningful connections across diverse audiences.",
        github_url: "https://github.com/Anshika-Kumari2003",
        linkedin_url: "https://www.linkedin.com/in/anshika-kumari-aa69112b0/",
        leader: false,
        createdAt: "2024-11-12T04:17:01.566Z",
        updatedAt: "2024-11-12T04:17:01.566Z",
        __v: 0,
      },
      {
        profile_image: {
          public_id: "avatars/hduookzhd9989bdogzoo",
          url: "https://res.cloudinary.com/dd1rpkqom/image/upload/v1731385186/avatars/hduookzhd9989bdogzoo.jpg",
        },
        _id: "6732d76213d01b8bc184b146",
        name: "Dipak kumar",
        department: "CSE-DS",
        designation: "PR",
        email_id: "dipakkr0426@gmail.com",
        batch: "2022-26",
        bio: "Ambitious data scientist in training, with a strong foundation in statistics, machine learning, and data analysis",
        github_url: "https://github.com/Dipak0426",
        linkedin_url: "https://www.linkedin.com/in/dipak-kumar-713b3027a/",
        leader: false,
        createdAt: "2024-11-12T04:19:46.955Z",
        updatedAt: "2024-11-12T04:19:46.955Z",
        __v: 0,
      },
      {
        profile_image: {
          public_id: "avatars/juzrvveffrtp1byukd1p",
          url: "https://res.cloudinary.com/dd1rpkqom/image/upload/v1731385338/avatars/juzrvveffrtp1byukd1p.jpg",
        },
        _id: "6732d7fa13d01b8bc184b14b",
        name: "Md Umam Adnan Khan",
        department: "IT",
        designation: "PR",
        email_id: "umamkhan9931@gmail.com",
        batch: "2022-26",
        bio: "A noobie in the field of Tech wandering to earn skills",
        github_url: "https://github.com/Umam-3289",
        linkedin_url: "www.linkedin.com/in/umam-khan-7213aa261",
        leader: false,
        createdAt: "2024-11-12T04:22:18.587Z",
        updatedAt: "2024-11-12T04:22:18.587Z",
        __v: 0,
      },
      {
        profile_image: {
          public_id: "avatars/uhm4wzupw5r81zt9hqfy",
          url: "https://res.cloudinary.com/dd1rpkqom/image/upload/v1731385792/avatars/uhm4wzupw5r81zt9hqfy.png",
        },
        _id: "6732d9c013d01b8bc184b150",
        name: "Rohan Choudhary",
        department: "CSE-DS",
        designation: "PR",
        email_id: "rohan5210work@gmail.com",
        batch: "2022-26",
        bio: "Ambitious B.Tech at Haldia Institute of Technology, Haldia, West Bengal, specializing in Data Science. Proficient in Python, R, Video Editing, Graphic Designing and SQL. Expertise in data analysis, machine learning, and data visualization. Passionate about using data to solve real-world problems",
        github_url: "https://github.com/rohanchoudhary5210",
        linkedin_url: "https://www.linkedin.com/in/rohanchoudhary5210/",
        leader: false,
        createdAt: "2024-11-12T04:29:52.573Z",
        updatedAt: "2024-11-12T04:29:52.573Z",
        __v: 0,
      },
      {
        profile_image: {
          public_id: "avatars/fatgfipqv5vcyvwv1sol",
          url: "https://res.cloudinary.com/dd1rpkqom/image/upload/v1731385993/avatars/fatgfipqv5vcyvwv1sol.jpg",
        },
        _id: "6732da8913d01b8bc184b155",
        name: "SAKSHI PRIYA",
        department: "CSE-DS",
        designation: "PR",
        email_id: "sakshipriya98010@gmail.com",
        batch: "2022-26",
        bio: "I'm a tech enthusiast passionate about bridging the gap between innovation and communication. As a PR , I'm dedicated to showcasing our club's groundbreaking projects and achievements.",
        github_url: "https://github.com/Sakshipriya01112003",
        linkedin_url: "https://www.linkedin.com/in/sakshi-priya-aa770a254/",
        leader: false,
        createdAt: "2024-11-12T04:33:13.706Z",
        updatedAt: "2024-11-12T04:33:13.706Z",
        __v: 0,
      },
      {
        profile_image: {
          public_id: "avatars/pgfpzbvampwwvmovoewm",
          url: "https://res.cloudinary.com/dd1rpkqom/image/upload/v1731387849/avatars/pgfpzbvampwwvmovoewm.jpg",
        },
        _id: "6732e1c913d01b8bc184b1e0",
        name: "Rehan Fazal",
        department: "CSE-DS",
        designation: "PR",
        email_id: "fazalrehan765@gmail.com",
        batch: "2022-26",
        bio: "Hey visitor, I am a part of the budding Public Relation team of DSCH Club.",
        github_url: "https://github.com/fazalrehan",
        linkedin_url: "linkedin.com/in/rehan-fazal-57a0ba326/",
        leader: false,
        createdAt: "2024-11-12T05:04:09.860Z",
        updatedAt: "2024-11-12T05:04:09.860Z",
        __v: 0,
      },
      {
        profile_image: {
          public_id: "avatars/wpo7aevcf46tfi7yeth0",
          url: "https://res.cloudinary.com/dd1rpkqom/image/upload/v1731386221/avatars/wpo7aevcf46tfi7yeth0.jpg",
        },
        _id: "6732db6e13d01b8bc184b15a",
        name: "Ankush Panja",
        department: "CSE-DS",
        designation: "Photographer",
        email_id: "panjaankush10@gmail.com",
        batch: "2022-26",
        bio: "Undergrad at Haldia Institute of Technology in Computer Science and Engineering with specialization in Data Science || Photographer at Data Science Club HIT || Interested in Machine Learning. || CSE-DS'26.",
        github_url: "https://github.com/Ankushgit-hub",
        linkedin_url:
          "https://www.linkedin.com/in/ankush-panja-89399223b?utm_source=share&utm_campaign=share_via&utm_content=profile&utm_medium=android_app",
        leader: false,
        createdAt: "2024-11-12T04:37:02.306Z",
        updatedAt: "2024-11-12T05:09:47.559Z",
        __v: 0,
      },
      {
        profile_image: {
          public_id: "avatars/tztwzfeopabqn0yxhaav",
          url: "https://res.cloudinary.com/dd1rpkqom/image/upload/v1731386353/avatars/tztwzfeopabqn0yxhaav.jpg",
        },
        _id: "6732dbf113d01b8bc184b15f",
        name: "Dipasha Mehta",
        department: "CSE-DS",
        designation: "Graphic Designer",
        email_id: "mehtadipasha7@gmail.com",
        batch: "2022-26",
        bio: "passionate about transforming ideas into visual stories, I chose graphic design to blend creativity with communication, making impactful designs that resonate.",
        github_url: "https://github.com/Dipasha-Mehta",
        linkedin_url: "https://www.linkedin.com/in/dipasha-mehta-0433b32b4",
        leader: false,
        createdAt: "2024-11-12T04:39:13.680Z",
        updatedAt: "2024-11-12T04:39:13.680Z",
        __v: 0,
      },
      {
        profile_image: {
          public_id: "avatars/crfrbiy3vitmmmts1ufm",
          url: "https://res.cloudinary.com/dd1rpkqom/image/upload/v1731386555/avatars/crfrbiy3vitmmmts1ufm.jpg",
        },
        _id: "6732dcbb13d01b8bc184b164",
        name: "Kumar Aditya Bidya",
        department: "CSE-DS",
        designation: "Graphic Designer",
        email_id: "adityastarboy09@gmail.com",
        batch: "2022-26",
        bio: "Graphic Designer, always thrilled to craft some graphics manually.",
        github_url: "https://github.com/Aditya27022004",
        linkedin_url: "https://www.linkedin.com/in/aditya-bidya-1b86ba242/",
        leader: false,
        createdAt: "2024-11-12T04:42:35.561Z",
        updatedAt: "2024-11-12T04:42:35.561Z",
        __v: 0,
      },
      {
        profile_image: {
          public_id: "avatars/ruia6zxi7baorknhdvnh",
          url: "https://res.cloudinary.com/dd1rpkqom/image/upload/v1731387005/avatars/ruia6zxi7baorknhdvnh.jpg",
        },
        _id: "6732de7e13d01b8bc184b1c8",
        name: "Anshu Kumar Dalal",
        department: "CSE-DS",
        designation: "Content Writer",
        email_id: "anshukumardalal@gmail.com",
        batch: "2022-26",
        bio: "Data science enthusiast skilled in decisively utilizing data into actionable insights and a strong foundation in machine learning, statistics and visualisation.",
        github_url: "https://github.com/Anshudalal941",
        linkedin_url: "https://www.linkedin.com/in/anshu-kumar-dalal",
        leader: false,
        createdAt: "2024-11-12T04:50:06.264Z",
        updatedAt: "2024-11-12T04:50:06.264Z",
        __v: 0,
      },
      {
        profile_image: {
          public_id: "avatars/mfpnhuasi398sd74rm1r",
          url: "https://res.cloudinary.com/dd1rpkqom/image/upload/v1731387707/avatars/mfpnhuasi398sd74rm1r.jpg",
        },
        _id: "6732e13c13d01b8bc184b1db",
        name: "Sahil Priyadarshi",
        department: "CSE-DS",
        designation: "Content Writer",
        email_id: "sahilpriyadarshivpn@gmail.com",
        batch: "2022-26",
        bio: "Twirling together literature and perspective seamlessly. Being called Content Writer effortlessly.",
        github_url: "NA",
        linkedin_url:
          "https://www.linkedin.com/in/sahil-priyadarshi-2101bb254?utm_source=share&utm_campaign=share_via&utm_content=profile&utm_medium=android_app",
        leader: false,
        createdAt: "2024-11-12T05:01:48.137Z",
        updatedAt: "2024-11-12T05:01:48.137Z",
        __v: 0,
      },
      {
        profile_image: {
          public_id: "avatars/rncdd9mbqeo81equsgdc",
          url: "https://res.cloudinary.com/dd1rpkqom/image/upload/v1731387542/avatars/rncdd9mbqeo81equsgdc.jpg",
        },
        _id: "6732e09713d01b8bc184b1d3",
        name: "Ravi Jaiswal",
        department: "CSE-DS",
        designation: "Video Editor",
        email_id: "ravijaiswal258852@gmail.com",
        batch: "2022-26",
        bio: "Passionate video editor skilled in crafting engaging stories with precision and creativity.",
        github_url: "https://github.com/jais-ravi",
        linkedin_url: "https://linkedin.com/in/ravi-jaiswal-445223271",
        leader: false,
        createdAt: "2024-11-12T04:59:03.080Z",
        updatedAt: "2024-11-12T04:59:03.080Z",
        __v: 0,
      },
      {
        profile_image: {
          public_id: "avatars/yyylvgyuh2oqarfncswg",
          url: "https://res.cloudinary.com/dd1rpkqom/image/upload/v1731406397/avatars/yyylvgyuh2oqarfncswg.jpg",
        },
        _id: "6733267d13d01b8bc184b39b",
        name: "Shashwat Kumar",
        department: "IT",
        designation: "Technical Member",
        email_id: "shashwatkr122@gmail.com",
        batch: "2023-27",
        bio: '"Web Developer & Problem Solver | Delivering scalable digital solutions."\n',
        github_url: "NA",
        linkedin_url:
          "https://www.linkedin.com/in/shashwat-kumar-37886128b?utm_source=share&utm_campaign=share_via&utm_content=profile&utm_medium=android_app",
        leader: false,
        createdAt: "2024-11-12T09:57:17.722Z",
        updatedAt: "2024-11-12T10:13:18.305Z",
        __v: 0,
      },
      {
        profile_image: {
          public_id: "avatars/wzby8uatbpyvofz33xpb",
          url: "https://res.cloudinary.com/dd1rpkqom/image/upload/v1731406833/avatars/wzby8uatbpyvofz33xpb.jpg",
        },
        _id: "67332bf213d01b8bc184b466",
        name: "Manavi Kumari",
        department: "CHE",
        designation: "Technical Member",
        email_id: "manavikumari18@gmail.com",
        batch: "2023-27",
        bio: "Curious data science and ML enthusiast, building skills to solve real-world problems and create a meaningful impact.\n",
        github_url: "https://github.com/Manavi-ku",
        linkedin_url: "https://www.linkedin.com/in/manavi-kumari/",
        leader: false,
        createdAt: "2024-11-12T10:20:34.239Z",
        updatedAt: "2024-11-12T10:20:34.239Z",
        __v: 0,
      },
      {
        profile_image: {
          public_id: "avatars/gvulauziue54omixy2xi",
          url: "https://res.cloudinary.com/dd1rpkqom/image/upload/v1731418268/avatars/gvulauziue54omixy2xi.jpg",
        },
        _id: "67332d9c13d01b8bc184b497",
        name: "Suman Kumar",
        department: "CSE-AIML",
        designation: "Technical Member",
        email_id: "sumankumar92530@gmail.com",
        batch: "2023-27",
        bio: "Exploring the unknown is the hobby of few and few comes under my category. \n\n",
        github_url: "https://github.com/sumankumar2024",
        linkedin_url: "NA",
        leader: false,
        createdAt: "2024-11-12T10:27:40.701Z",
        updatedAt: "2024-11-12T13:31:08.753Z",
        __v: 0,
      },
      {
        profile_image: {
          public_id: "avatars/klprxhd2o1cmktwwoce6",
          url: "https://res.cloudinary.com/dd1rpkqom/image/upload/v1731407865/avatars/klprxhd2o1cmktwwoce6.jpg",
        },
        _id: "67332ff913d01b8bc184b4ce",
        name: "Sulogno Sarkar ",
        department: "CSE-DS",
        designation: "Technical Member",
        email_id: "rhitsarkar2003@gmail.com",
        batch: "2023-27",
        bio: '"As a tech team member in my college\'s data science club, I bring a solid foundation in programming, automation, and data-driven problem-solving. My experience includes developing automation scripts, building trading strategies, and exploring innovative applications of data science. Skilled in languages like Python and C, I focus on creating impactful solutions that leverage automation and data insights.\n\nIâ€™m passionate about advancing my technical skills, contributing to team projects, and exploring new opportunities in the data science field to drive meaningful outcomes in both academic and professional settings.\n"\n',
        github_url: "https://github.com/sulogno",
        linkedin_url:
          "https://www.linkedin.com/in/sulogno-sarkar-8007a82b6?utm_source=share&utm_campaign=share_via&utm_content=profile&utm_medium=android_app",
        leader: false,
        createdAt: "2024-11-12T10:37:45.935Z",
        updatedAt: "2024-11-12T10:37:45.935Z",
        __v: 0,
      },
      {
        profile_image: {
          public_id: "avatars/xktu7i34rley3bckffnt",
          url: "https://res.cloudinary.com/dd1rpkqom/image/upload/v1737666422/avatars/xktu7i34rley3bckffnt.jpg",
        },
        _id: "6733311113d01b8bc184b4d3",
        name: "Yash Kumar",
        department: "CSE-CS",
        designation: "Technical Member",
        email_id: "yash852131@gmail.com",
        batch: "2023-27",
        bio: "I am interested in coding.\n",
        github_url: "https://github.com/Yash636363",
        linkedin_url: "https://www.linkedin.com/in/yash-kumar-45586429a",
        leader: false,
        createdAt: "2024-11-12T10:42:25.849Z",
        updatedAt: "2025-01-23T21:07:03.103Z",
        __v: 0,
      },
      {
        profile_image: {
          public_id: "avatars/qj2fx6w2tuctc4dlumg3",
          url: "https://res.cloudinary.com/dd1rpkqom/image/upload/v1731408345/avatars/qj2fx6w2tuctc4dlumg3.jpg",
        },
        _id: "673331d913d01b8bc184b4ef",
        name: "AMAN KUMAR ",
        department: "CSE-DS",
        designation: "PR",
        email_id: "amandbg8298@gmail.com",
        batch: "2023-27",
        bio: "Data science freshers.Ready to contribute in the technical field and enhance my knowledge along with upskilling.Optimistic towards my goal.\n",
        github_url: "NA",
        linkedin_url: "NA",
        leader: false,
        createdAt: "2024-11-12T10:45:45.793Z",
        updatedAt: "2024-11-12T10:45:45.793Z",
        __v: 0,
      },
      {
        profile_image: {
          public_id: "avatars/zmvm8frqpwbpglzdbwgf",
          url: "https://res.cloudinary.com/dd1rpkqom/image/upload/v1731408684/avatars/zmvm8frqpwbpglzdbwgf.jpg",
        },
        _id: "6733332c13d01b8bc184b520",
        name: "HAMMAD WAFEE",
        department: "CSE-DS",
        designation: "PR",
        email_id: "anamta.anamta6456@gmail.com",
        batch: "2023-27",
        bio: "Working as PR in DSCH \n",
        github_url: "https://github.com/hammadwafee",
        linkedin_url:
          "https://www.linkedin.com/in/hammad-wafee-72726129b?utm_source=share&utm_campaign=share_via&utm_content=profile&utm_medium=ios_app",
        leader: false,
        createdAt: "2024-11-12T10:51:24.363Z",
        updatedAt: "2024-11-12T10:51:24.363Z",
        __v: 0,
      },
      {
        profile_image: {
          public_id: "avatars/gobby7b6wfjel37ow90h",
          url: "https://res.cloudinary.com/dd1rpkqom/image/upload/v1731408921/avatars/gobby7b6wfjel37ow90h.jpg",
        },
        _id: "6733341913d01b8bc184b525",
        name: "Nishant Nirmal ",
        department: "CSE-DS",
        designation: "PR",
        email_id: "nishantnirmal.4245@gmail.com",
        batch: "2023-27",
        bio: "A motivated Data Science Fresher looking to leverage my programming skills in Python and R knowledge of data visualizations to effectively analyze, interpret, and present insights in an accurate and meaningful way.\n",
        github_url: "https://github.com/Nishantnirmal4245",
        linkedin_url:
          "https://www.linkedin.com/in/nishant-nirmal-2198b52a7?utm_source=share&utm_campaign=share_via&utm_content=profile&utm_medium=android_app",
        leader: false,
        createdAt: "2024-11-12T10:55:21.667Z",
        updatedAt: "2024-11-12T10:55:21.667Z",
        __v: 0,
      },
      {
        profile_image: {
          public_id: "avatars/gx6kevmt8tjynxu4a6mt",
          url: "https://res.cloudinary.com/dd1rpkqom/image/upload/v1731409159/avatars/gx6kevmt8tjynxu4a6mt.jpg",
        },
        _id: "6733350713d01b8bc184b52a",
        name: "Shailendra Kumar ",
        department: "CSE-DS",
        designation: "PR",
        email_id: "shailendra.deepak3012@gmail.com",
        batch: "2023-27",
        bio: "I love technology and am involved in my college's technical club where I work with people who are similar to me on interesting projects and events. I am focused on learning new skills and I am able to deal with problems so I enjoy putting myself in situations where I am pushed to grow and use my skills in actual practice.\n",
        github_url: "https://github.com/Shailendra3012",
        linkedin_url: "NA",
        leader: false,
        createdAt: "2024-11-12T10:59:19.946Z",
        updatedAt: "2024-11-12T10:59:19.946Z",
        __v: 0,
      },
      {
        profile_image: {
          public_id: "avatars/o3rzzsvok4gvsb63lega",
          url: "https://res.cloudinary.com/dd1rpkqom/image/upload/v1731409741/avatars/o3rzzsvok4gvsb63lega.jpg",
        },
        _id: "6733374d13d01b8bc184b546",
        name: "Shubham",
        department: "CSE-DS",
        designation: "PR",
        email_id: "shubhamsks9534@gmail.com",
        batch: "2023-27",
        bio: "I chose this profession Because I have Skills to Manage the team and want to Develope it in  to Next level .\n",
        github_url: "NA",
        linkedin_url: "NA",
        leader: false,
        createdAt: "2024-11-12T11:09:01.492Z",
        updatedAt: "2024-11-12T11:09:01.492Z",
        __v: 0,
      },
      {
        profile_image: {
          public_id: "avatars/s18o5aifg2wfy3fvdsk1",
          url: "https://res.cloudinary.com/dd1rpkqom/image/upload/v1731409959/avatars/s18o5aifg2wfy3fvdsk1.jpg",
        },
        _id: "6733382713d01b8bc184b54b",
        name: "SHIVAM KUMAR GUPTA",
        department: "CSE-DS",
        designation: "PR",
        email_id: "shivamkumargupta109@gmail.com",
        batch: "2023-27",
        bio: "Shivam Kumar Gupta, a second-year Computer Science Engineering student, currently serves as the PR member in the Data Science Club at HIT. With strong communication skills and the ability to engage effectively, I am also actively exploring the tech field through web development.\n",
        github_url: "https://github.com/devLover-Shivam",
        linkedin_url:
          "https://www.linkedin.com/in/shivam-kumar-gupta-07a9a027b?utm_source=share&utm_campaign=share_via&utm_content=profile&utm_medium=android_app",
        leader: false,
        createdAt: "2024-11-12T11:12:39.997Z",
        updatedAt: "2024-11-12T11:12:39.997Z",
        __v: 0,
      },
      {
        profile_image: {
          public_id: "avatars/bkulkrb032hui8aczyn0",
          url: "https://res.cloudinary.com/dd1rpkqom/image/upload/v1731410222/avatars/bkulkrb032hui8aczyn0.jpg",
        },
        _id: "6733392f13d01b8bc184b550",
        name: "Srishti Kumari ",
        department: "CSE-DS",
        designation: "PR",
        email_id: "srishtik717@gmail.com",
        batch: "2023-27",
        bio: "Passionate About Data-Driven Decision Making\n",
        github_url: "https://github.com/Srishtik-ui",
        linkedin_url: "https://www.linkedin.com/in/srishti-kumari-60a8502a6/",
        leader: false,
        createdAt: "2024-11-12T11:17:03.225Z",
        updatedAt: "2024-11-12T11:17:03.225Z",
        __v: 0,
      },
      {
        profile_image: {
          public_id: "avatars/vkadzf3tywq4a1cemrpb",
          url: "https://res.cloudinary.com/dd1rpkqom/image/upload/v1731418334/avatars/vkadzf3tywq4a1cemrpb.jpg",
        },
        _id: "673339b313d01b8bc184b56b",
        name: "Tripti Rani",
        department: "CSE-DS",
        designation: "PR",
        email_id: "ranitripti8732@gmail.com",
        batch: "2023-27",
        bio: "Aspiring data science student\n",
        github_url: "NA",
        linkedin_url: "www.linkedin.com/in/ tripti-rani-ab1184308",
        leader: false,
        createdAt: "2024-11-12T11:19:15.605Z",
        updatedAt: "2024-11-12T13:32:15.282Z",
        __v: 0,
      },
      {
        profile_image: {
          public_id: "avatars/mvnccxtuq6xa6dchqbxw",
          url: "https://res.cloudinary.com/dd1rpkqom/image/upload/v1731410588/avatars/mvnccxtuq6xa6dchqbxw.jpg",
        },
        _id: "67333a9d13d01b8bc184b586",
        name: "Anuradha Kumari ",
        department: "CSE-AIML",
        designation: "Graphic Designer",
        email_id: "krianuradha024@gmail.com",
        batch: "2023-27",
        bio: "Ambitious B.Tech student at Haldia Institute of Technology, Haldia, West Bengal, specializing in Artificial Intelligence. Proficient in Graphic Designing . Aspiring Software engineer learning Web development and DSA.\n",
        github_url: "https://github.com/anuradha-kri",
        linkedin_url: "https://www.linkedin.com/in/anuradha-kumari-b453a02b5/",
        leader: false,
        createdAt: "2024-11-12T11:23:09.373Z",
        updatedAt: "2024-11-12T11:23:09.373Z",
        __v: 0,
      },
      {
        profile_image: {
          public_id: "avatars/tsmcq9ddzfti74qsacrj",
          url: "https://res.cloudinary.com/dd1rpkqom/image/upload/v1731410893/avatars/tsmcq9ddzfti74qsacrj.jpg",
        },
        _id: "67333bce13d01b8bc184b5b7",
        name: "Soma Senapati ",
        department: "CSE-DS",
        designation: "Graphic Designer",
        email_id: "somasenapati683@gmail.com",
        batch: "2023-27",
        bio: "Ambitious B.Tech student at Haldia Institute of Technology, Haldia, West Bengal, specializing in Data Science . Proficient in Graphic Designing and PR skills . Aspiring Software engineer learning Python and DSA.\n",
        github_url: "NA",
        linkedin_url: "https://www.linkedin.com/in/soma-senapati-1328892ba",
        leader: false,
        createdAt: "2024-11-12T11:28:14.046Z",
        updatedAt: "2024-11-12T11:28:14.046Z",
        __v: 0,
      },
      {
        profile_image: {
          public_id: "avatars/hpe2pqbdgwgybm94x6cw",
          url: "https://res.cloudinary.com/dd1rpkqom/image/upload/v1731416285/avatars/hpe2pqbdgwgybm94x6cw.jpg",
        },
        _id: "673350dd13d01b8bc184b608",
        name: "Sumana Ghosh",
        department: "CSE-DS",
        designation: "Graphic Designer",
        email_id: "gsumana722160@gmail.com",
        batch: "2023-27",
        bio: "Ambitious B.Tech student at Haldia Institute of Technology, Haldia, West Bengal, specializing in Data Science. Proficient in Graphic Designing . Aspiring Software engineer learning Web development and DSA.",
        github_url: "NA",
        linkedin_url: "https://www.linkedin.com/in/sumana-ghosh-767571288/",
        leader: false,
        createdAt: "2024-11-12T12:58:05.740Z",
        updatedAt: "2024-11-12T13:25:46.592Z",
        __v: 0,
      },
      {
        profile_image: {
          public_id: "avatars/ynkgvt0jb5dnpvbis3ok",
          url: "https://res.cloudinary.com/dd1rpkqom/image/upload/v1731416576/avatars/ynkgvt0jb5dnpvbis3ok.jpg",
        },
        _id: "6733520113d01b8bc184b60d",
        name: "Sourasish Purkait",
        department: "CSE-AIML",
        designation: "Graphic Designer",
        email_id: "sourasishpurkait031@gmail.com",
        batch: "2023-27",
        bio: " With a keen eye for detail and a passion for aesthetics, as a graphic designer, I turns concepts into polished, impactful designs.",
        github_url: "NA",
        linkedin_url:
          "https://www.linkedin.com/in/sourasish-purkait-5742a9297?utm_source=share&utm_campaign=share_via&utm_content=profile&utm_medium=android_app",
        leader: false,
        createdAt: "2024-11-12T13:02:57.271Z",
        updatedAt: "2024-11-12T13:25:29.906Z",
        __v: 0,
      },
      {
        profile_image: {
          public_id: "avatars/ydidsejgisbgj4edjh5w",
          url: "https://res.cloudinary.com/dd1rpkqom/image/upload/v1731416880/avatars/ydidsejgisbgj4edjh5w.jpg",
        },
        _id: "6733533013d01b8bc184b642",
        name: "Gopal Bharti",
        department: "EE",
        designation: "Content Writer",
        email_id: "bhartigopal132@gmail.com",
        batch: "2023-27",
        bio: "Content Strategist & Writer | Expert in creating engaging articles, blogs, & web copy | Turning complex ideas into clear, compelling content.",
        github_url: "https://github.com/Gopal4964",
        linkedin_url:
          "https://www.linkedin.com/in/gopal-bharti-27bb0b2a5?utm_source=share&utm_campaign=share_via&utm_content=profile&utm_medium=android_app",
        leader: false,
        createdAt: "2024-11-12T13:08:00.686Z",
        updatedAt: "2024-11-12T13:08:00.686Z",
        __v: 0,
      },
      {
        profile_image: {
          public_id: "avatars/ulxbiivbq7jhnxb48caa",
          url: "https://res.cloudinary.com/dd1rpkqom/image/upload/v1731417020/avatars/ulxbiivbq7jhnxb48caa.jpg",
        },
        _id: "673353bc13d01b8bc184b647",
        name: "Harshita Smriti ",
        department: "CSE-AIML",
        designation: "Content Writer",
        email_id: "harshitasmriti@gmail.com",
        batch: "2023-27",
        bio: "I love content writing and am also keen about AI-ML.",
        github_url: "https://github.com/HarshitaSmriti",
        linkedin_url:
          "https://www.linkedin.com/in/harshita-smriti-967a1b27a?utm_source=share&utm_campaign=share_via&utm_content=profile&utm_medium=android_app",
        leader: false,
        createdAt: "2024-11-12T13:10:20.759Z",
        updatedAt: "2024-11-12T13:10:20.759Z",
        __v: 0,
      },
      {
        profile_image: {
          public_id: "avatars/r59nvnveahdt6mkypdgx",
          url: "https://res.cloudinary.com/dd1rpkqom/image/upload/v1731417140/avatars/r59nvnveahdt6mkypdgx.jpg",
        },
        _id: "6733543413d01b8bc184b64c",
        name: "Sumit Shekhar ",
        department: "CSE-DS",
        designation: "Content Writer",
        email_id: "sumitshekhar22091990@gmail.com",
        batch: "2023-27",
        bio: "Enthusiastic content writer with a keen eye for detail and a passion for crafting engaging narratives.",
        github_url: "NA",
        linkedin_url:
          "https://www.linkedin.com/in/sumit-shekhar-05097426a?utm_source=share&utm_campaign=share_via&utm_content=profile&utm_medium=android_app",
        leader: false,
        createdAt: "2024-11-12T13:12:20.719Z",
        updatedAt: "2024-11-12T13:25:08.437Z",
        __v: 0,
      },
      {
        profile_image: {
          public_id: "avatars/n37ob3o4x0xxnn8vx4iv",
          url: "https://res.cloudinary.com/dd1rpkqom/image/upload/v1731417283/avatars/n37ob3o4x0xxnn8vx4iv.jpg",
        },
        _id: "673354c313d01b8bc184b651",
        name: "Tanay Srivastav ",
        department: "CSE-CS",
        designation: "Content Writer",
        email_id: "tanaysrivastavk@gmail.com",
        batch: "2023-27",
        bio: "I am a engineer with passion for writing content.",
        github_url: "https://github.com/Tanay4002",
        linkedin_url: "https://www.linkedin.com/in/tanay-srivastav-6934262a3",
        leader: false,
        createdAt: "2024-11-12T13:14:43.497Z",
        updatedAt: "2024-11-12T13:14:43.497Z",
        __v: 0,
      },
      {
        profile_image: {
          public_id: "avatars/ufxla5iutotkg68amw1g",
          url: "https://res.cloudinary.com/dd1rpkqom/image/upload/v1731417797/avatars/ufxla5iutotkg68amw1g.jpg",
        },
        _id: "6733563913d01b8bc184b69d",
        name: "Rohan Kumar",
        department: "CSE-DS",
        designation: "Video Editor",
        email_id: "rohankr1029@gmail.com",
        batch: "2023-27",
        bio: "Enthusiastic about coding and video editing.",
        github_url: "NA",
        linkedin_url:
          "https://www.linkedin.com/in/rohan-kumar-8b1195253?utm_source=share&utm_campaign=share_via&utm_content=profile&utm_medium=android_app",
        leader: false,
        createdAt: "2024-11-12T13:20:57.310Z",
        updatedAt: "2024-11-12T13:24:49.557Z",
        __v: 0,
      },
    ],
  };
  
  const categorizeMembers = (members: Member[]) => {
    const coreTeam: Member[] = [];
    const mediaTeam: Record<string, Member[]> = {
      photographer: [],
      graphicDesigner: [],
      contentWriter: [],
      videoEditor: [],
    };
    const prTeam: Member[] = [];
  
    members.forEach((member) => {
      const designation = member.designation.toLowerCase();
  
      if (
        designation.includes("president") ||
        designation.includes("vice-president") ||
        designation.includes("secretary") ||
        designation.includes("treasurer") ||
        designation.includes("technical head") ||
        designation.includes("event head")
      ) {
        coreTeam.push(member);
      } else if (designation.includes("media head")) {
        mediaTeam.mediaHead.push(member);
      } else if (designation.includes("photographer")) {
        mediaTeam.photographer.push(member);
      } else if (designation.includes("graphic designer")) {
        mediaTeam.graphicDesigner.push(member);
      } else if (designation.includes("content writer")) {
        mediaTeam.contentWriter.push(member);
      } else if (designation.includes("video editor")) {
        mediaTeam.videoEditor.push(member);
      } else if (designation.includes("pr") || designation.includes("public relation")) {
        prTeam.push(member);
      }
    });
  
    return { coreTeam, mediaTeam, prTeam };
  };

  
  export const  { coreTeam, mediaTeam, prTeam } = categorizeMembers(data.members);
  
  console.log("Core Team:", coreTeam);
  console.log("Media Team:", mediaTeam);
  console.log("PR Team:", prTeam);
  