name: Build and Deploy to Cloud Run

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v1
        with:
          credentials_json: ${{ secrets.GCP_CREDENTIALS }}

      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v1

      - name: Debug .env Creation
        run: |
          echo "NEXT_PUBLIC_SERVER_URI=\"${{ secrets.NEXT_PUBLIC_SERVER_URI }}\"" > .env
          echo "ACCESS_TOKEN=\"$(echo ${{ secrets.ACCESS_TOKEN_BASE64 }} | base64 -d)\"" >> .env
          echo "NEXT_PUBLIC_BASE_URL=\"${{ secrets.NEXT_PUBLIC_BASE_URL }}\"" >> .env
          echo "NEXT_PUBLIC_ENV=\"${{ secrets.NEXT_PUBLIC_ENV }}\"" >> .env
          cat .env || echo "Failed to create .env"

      - name: Build Docker Image
        run: |
          docker build -t gcr.io/${{ secrets.GCP_PROJECT_ID }}/gdg-client .
        env:
          GCP_PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}

      - name: Push Docker Image
        run: |
          gcloud auth configure-docker
          docker push gcr.io/${{ secrets.GCP_PROJECT_ID }}/gdg-client

      - name: Deploy to Cloud Run
        run: |
          gcloud run deploy gdg-client \
            --image gcr.io/${{ secrets.GCP_PROJECT_ID }}/gdg-client \
            --region asia-southeast1 \
            --platform managed \
            --set-env-vars "NEXT_PUBLIC_SERVER_URI=${{ secrets.NEXT_PUBLIC_SERVER_URI }},ACCESS_TOKEN=$(echo ${{ secrets.ACCESS_TOKEN_BASE64 }} | base64 -d),NEXT_PUBLIC_BASE_URL=${{ secrets.NEXT_PUBLIC_BASE_URL }},NEXT_PUBLIC_ENV=${{ secrets.NEXT_PUBLIC_ENV }}"
